### ISSUE TITLE
Quick question about Generated Source Code

### ISSUE THREAD

**Issue by rastographics** [bvcms/bvcms#107]
Do the objects in CMSData/Generated get generated from the database schema?
If so, when and how does that happen? Is there an external tool that does that somewhere?

I'm just trying to digest the source code...

**Comment by rastographics** [comment]
OK after looking around forever I finally see it right after I posted my question.
I was looking in the main Solution and didn't notice another separate Solution in DbmlBuilder.

Feel free to close this out unless you wanted to chime in anything about DbmlBuilder. 

Thanks

**Comment by davidcarroll** [comment]
It is a command line tool. The current dir has to be the CmsData directory. Any new tables, views, functions, etc. have to be included in the project from the solution explorer in visual studio (view all files, right click new file, include)

**Comment by davidcarroll** [comment]
We will need a database so we can rebuild the database create scripts from the database schema. Or you can just send a change script to add the columns, etc. We use Red-Gate tools to simplify that whole process.
