### ISSUE TITLE
"Create Sub-Group" dialog box behavior on Enter 

### ISSUE THREAD

**Issue by rastographics** [bvcms/bvcms#112]
[This video](https://vimeo.com/164283679/ef32e51647) shows what happens when you press Enter on keyboard instead of clicking OK on the dialog box. (From does regular POST instead of jquery post)

Expected behavior: whether clicking OK or hitting Enter, the form should submit the same way.

Do you want me to fix this and submit PR?

EDIT: video is still converting...

**Comment by davidcarroll** [comment]
I get a 404 on the video link. But, I would be very happy for you to fix this!

**Comment by rastographics** [comment]
Video was still being processed.

Here's the PR: https://github.com/bvcms/bvcms/pull/113

Changes live on http://dev.nwbbc.org:44401
user: admin
password: touchpoint.1
