### ISSUE TITLE
Python GetPerson is returning CmsDataPerson instead of APIPerson

### ISSUE THREAD

**Issue by jkrrv** [bvcms/bvcms#1174]
I'm hoping I'm just confused. 

It appears that a call to the python function `model.GetPerson()` is returning a CmsData Person instead of an API Person, which is notably confusing.

[This script](https://my.tenth.org/PyScript/_JamesTesting) is just a printing of the output from one such call.  Notably, the `FamilyAddress` and `PersonalAddress` fields are missing, but there's a huge number of additional fields that aren't in the API Person documentation (or source code ????). 

From what I can tell, this changed in the last week, because some of our scripts are now broken, but I'm not positive about that. 

If this is how this is supposed to work, that's fine--it's actually easier for me to work with the CmsData Person, but I do want to make sure I'm writing our scripts to a non-moving API target. 

Thanks!

**Comment by brondavies** [comment]
Sorry about the confusion.  Yes, this is a permanent change to the Python API. APIPerson will be phased out sometime in the future.

**Comment by jkrrv** [comment]
Cool. Thanks!
