### ISSUE TITLE
Contribution statement

### ISSUE THREAD

**Issue by jkcpa** [bvcms/bvcms#162]
Have two situations currently. The first is that an individual had only in-kind gifts during the year which we did not value. Those don't show up on the statement unless you put at least a penny value on the item. Second is we have several individuals that you can print their  contribution statements from their record, but when you run contribution statements in bulk they  aren't included in the list. Electronic only is not checked

**Comment by davidcarroll** [comment]
Make sure you are running the latest version of the software. We just tested this and it is working fine for us. 

Since we don't have access to your database, we cannot provide support. But the typical reason a statement does not print is because there is no address. There is also a default minimum contribution amount. All of this is in the documentation.

Consider allowing us to host your church's database. The fees are very reasonable.

**Comment by jkcpa** [comment]
1. Thank you for the quick response
2. Further investigation (after posting) revealed that office staff had entered PO Box addresses into the field AddressLineTwo rather than AddressLineOne, leaving AddressLineOne null in the database. Moving the data to the AddressLineOne field solved the issue.
3. Consider that gifts in kind won't have a value in the database. Example - a member works for a company that sells video monitors used for advertising kiosks in malls. He donates several large surplus monitors for use in the church foyer. It is typically left up to the donor to substantiate the value - the church just acknowledges the quantity, brand, model and condition (new or used) of the items. If he also has cash contributions, both print fine on the statement. If he has only in-kind with no assigned value, nothing prints. Granted, a rare scenario, but still one that happened.
4. Our church annually supports the software development through designated contributions to Bellevue. We appreciate everything you do (and how well you do it!). However, at this time we feel self hosting give us flexibility in certain areas of data access that would be lost if the data did not reside on our servers.
Again, thank you for the quick response and all you and your team put into the software. Your comments also helped me track down what the issue was on the last problem.
Jim

Sent from my iPhone

On Jan 15, 2017, at 6:27 AM, David Carroll <notifications@github.com<mailto:notifications@github.com>> wrote:


Make sure you are running the latest version of the software. We just tested this and it is working fine for us.

Since we don't have access to your database, we cannot provide support. But the typical reason a statement does not print is because there is no address. There is also a default minimum contribution amount. All of this is in the documentation.

Consider allowing us to host your church's database. The fees are very reasonable.
