### ISSUE TITLE
How to upgrade the database Schema

### ISSUE THREAD

**Issue by ekabvunye** [bvcms/bvcms#164]
Hello
I have downloaded and set up your system on a test machine to review the code. However I have found that there are continuous changes to the schema on the source. Are there any scripts or steps I need to take so that I just take changes to the database schema and upgrade without setting the whole system from scratch.

Regards
Emmanuel

**Comment by davidcarroll** [comment]
I use Red-Gate SQL compare to generate a schema change script. It is expensive. But you can also do this with a free open source tool called db compare at 
https://dbcompare.codeplex.com/

You would let cmsweb generate a new database, then use that tool above to compare the new with your db and generate a script to bring your db up to date with the code.

**Comment by ekabvunye** [comment]
Many thanks. I will give it a try
