### ISSUE TITLE
Error Re-building CMSWeb on the latest Source

### ISSUE THREAD

**Issue by ekabvunye** [bvcms/bvcms#170]
Hi
I have downloaded your latest version of the bvcms source code. When I tried to re-build the cmsweb on VS 2017 I got the following 3 errors attached. Can you assist
[Error Rebuilding.docx](https://github.com/bvcms/bvcms/files/971794/Error.Rebuilding.docx)

Regards

**Comment by davidcarroll** [comment]
I'll try to look at it this weekend. We are not having a problem here. The error is about a missing NuGet package. I'll have to install on a clean machine to see since all is well in my development environment.

**Comment by ekabvunye** [comment]
Thanks. It looks like there is a missing nugget.
Will wait to hear from you.
Thanks

**Comment by davidcarroll** [comment]
I have pushed a fix for this missing Nuget RestSharp package. Not sure why it was working for me, but I installed on a clean development environment and it failed just as you indicated. The fix was easy, just check the box for RestSharp in the NuGet package manager.

**Comment by ekabvunye** [comment]
Many thanks. I will download the latest source and test.

Regards
