### ISSUE TITLE
Visio Studio - set up issues

### ISSUE THREAD

**Issue by GracieChao** [bvcms/bvcms#230]
Hi! I'm new to GitHub, so bear with me as I'm learning.  I'm a sql developer and my church has asked me to help create some custom sql reports.  I followed the directions in the Quick Start Guide and when I try to clone a repository in Visio Studio I get the below error messages.

Is there special access I need to request in order to access the repository?  I tried to contact Touchpoint software and they directed me to the GitHub community.

Error encountered while cloning the remote repository: Git failed with a fatal error.
unable to access 'https://github.com/bvcms/bvcms.git/': error:14077419:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert access denied

Error encountered while cloning the remote repository: Git failed with a fatal error.
unable to access 'https://github.com/bvcms/bvcms/': error:14077419:SSL routines:SSL23_GET_SERVER_HELLO:tlsv1 alert access denied

**Comment by aternex** [comment]
Are you using git for windows or another git client to clone the repository? I have seen similar errors when searching on google and they typically get resolved by updating the version of git on your machine and making sure your network configuration (proxy servers) is setup correctly. Also, I notice you are apparently requesting the repo on tls 1.0. You might refer to this article from github about the changes from TLS 1 to a more recent version of TLS https://blog.github.com/2018-02-23-weak-cryptographic-standards-removed/ as it could be related.

**Comment by GracieChao** [comment]
Thank you for your help!  I am using git windows and after googling the
issue, I downloaded the git credential manager for windows.   I am now able
to successfully clone the bcvms repository in Visio Studio!  I also
downloaded sql server 2016 express. I haven't been successful in connecting
to the testdb. I also do not see any instructions on how to set up the
database connection into our our church's database.  Is the URL to database
posted anywhere?

I apologize in advance for the numerous questions.

Blessings,
Grace

**Comment by davidcarroll** [comment]
You can't access your live database directly with SQL Server but you can make arrangements to have a nightly backup downloaded to your own Rackspace CloudFiles account. This way you can compose your scripts locally on your own development machine and once you are satisfied, you can then use your Touchpoint account to install your script on your church's database. Of course, Touchpoint would require that a person with both Admin and Finance roles approve this.

See the following help documentation for more on this:
http://docs.touchpointsoftware.com/CustomProgramming/index.html#writing-your-own-scripts
