### ISSUE TITLE
Question: Adding SuffixCode to IPad Checkin Page

### ISSUE THREAD

**Issue by hkouns** [bvcms/bvcms#28]
I am attempting to add the SuffixCode to the IPad Checkin page so that we can differentiate between Jr and Sr with the same name.
I have tried updating the PersonInfo Class in Rollsheet Model to add a SuffixCode but I am having a difficult getting the parameter to update from the Person model.
I have also tried updating OrgMembersAsOfDate.cs and OrgVisitorsAsOfDate.cs to add a column for SuffixCode... but then I get an invalid column error on compile.

https://github.com/hkouns/bvcms/commit/cc0864c1dc2bc812bc7d68aad10c9e7bd29b31c5#diff-a703fd5b5d60c553ba3dc06b0d464730R78

I know I am missing something simple... Suggestions?

**Comment by davidcarroll** [comment]
Both the OrgMembersAsOfDate and OrgVisitorsAsOfDate are generated files using our DbmlBuilder project. Both of these are SQL UserDefinedFunctions which are the source code for these generated files. These require a dbschema change which has to be coordinated across the development team.

We'll put this on our backlog list to implement.

**Comment by davidcarroll** [comment]
This is on our backlog, closing this for now until it rises to the top again.
