### ISSUE TITLE
Database creation

### ISSUE THREAD

**Issue by jkcpa** [bvcms/bvcms#44]
Noticed that the current build refereces "ElmahDb" on this line
Util.GetConnectionString2("ElmahDb"), Util.ConnectionString);
in CreateDatabase.cs
This seems to cause an error - Error in BuildElmahDb.sql: Cannot open database "ElmahDb" requested by the login. The login failed. Login failed for user 'sa'.

**Comment by drmohundro** [comment]
What is the content of your "ConnectionStrings.config" file? It should be under "<checkout dir>\CmsWeb\ConnectionStrings.config". See the [current version here](https://github.com/bvcms/bvcms/blob/master/CmsWeb/ConnectionStrings.config).

By default, the build does not use the "sa" user but instead uses integrated authentication (i.e. your Windows account).

**Comment by jkcpa** [comment]
Okay, here's the details of what I ran into:

Every month or so, I sync through Github (making sure that the difference between the new web.config file and mine are only what's needed to customize to my install, and I double-check the ConnectionStrings.config file for the same type of information) and then go onto the SQL server and detach the ELMAH database and move it. Then I build the new download and (using my configuration file with the database name changed slightly) I run the build and let the software create a new ELMAH database as well as the CMS and CMSi databases. I use these to do a schema compare and update the production database schema. When I'm done, I delete the databases I added and re-attach the ELMAH database, then change the config file database name back (also where it's referenced in the web.config file).

On this last go-round (yesterday), I could not get IE to run the new build through Visual Studio. I switched to FireFox and it had trouble (as I sent in) with the ELMAH database creation. I checked the code and found that I could have an existing ELMAH file and it would still create the new database files, so I brought the old ELHAH database back online and everything worked exactly as expected. So really, there's at least two issues present - it's always worked with IE before and currently it doesn't (with IIS Express, it's possible that is something on my machine), and there's some hick-up in the creation of the ELMAH database.

Jim

**Comment by drmohundro** [comment]
Thanks @jkcpa for the detailed bug report - that helped track down the issue!

One problem was related to a mistype I had put in a few weeks back related to "ElmahDb" - the name should have just been "Elmah". Also, regarding your observations around it not working with IE - that is actually because IE requests the favicon.ico on the initial request whereas both Chrome and Firefox don't until after the initial request completes. It was a timing issue. That should also be fixed as well.

Let me know if you still see any issues.

**Comment by jkcpa** [comment]
You guys are awesome!

Thanks.

Jim
