### ISSUE TITLE
Nullreferenceexception

### ISSUE THREAD

**Issue by jkcpa** [bvcms/bvcms#51]
Clean download of current build produces a null reference exception in the utility extensions module (see attached)
![screen1](https://cloud.githubusercontent.com/assets/5313367/8815992/c2c0d948-2fd5-11e5-924a-35412372d894.png)
![screen2](https://cloud.githubusercontent.com/assets/5313367/8815993/c2c0f018-2fd5-11e5-98fe-050599dffaa8.png)

**Comment by davidcarroll** [comment]
Try putting this line in your web.config AppSettings
That should take care of it until we get the code fixed to ignore this.
<add key="RebootDbInProgress" value="%USERPROFILE%\Documents\RebootDb.txt"
/>

**Comment by jkcpa** [comment]
I was just experimenting with adding a key with that title - didn't know what value to give it.
Thanks.

**Comment by jkcpa** [comment]
That did the trick. Thank you (again).
