### ISSUE TITLE
BVCMS install

### ISSUE THREAD

**Issue by vanutama** [bvcms/bvcms#70]
Hi, my church is want to try as many as possible web based church management before using the one we like. So, we found BVCMS.
I just have some question about BVCMS Developer Quick Start Guide:
1. Did I need Windows Server or any Windows machine is fine?
2. Are there any video tutorial or with picture to help us install BVCMS?

**Comment by davidcarroll** [comment]
Our database is a SqlServer 2012 R2, Our Web Servers are Windows Server 2008 R2.

We cannot provide support for self-hosted installation.

If this is beyond your expertise, we are happy to provide hosting and support at http://www.touchpointsoftware.com for a very reasonable fee.

**Comment by vanutama** [comment]
Ok thanks
