### ISSUE TITLE
Internet connection

### ISSUE THREAD

**Issue by allanregistos** [bvcms/bvcms#80]
I am testing bvcms, today, but when I disconnect the network, then starting bvcms, it will throw an error in this part of code:

 public static HttpWebResponse GetHttpResponse(this HttpWebRequest request)
        {
            try
            {
                return (HttpWebResponse) request.GetResponse();
            }
            catch (WebException ex)
            {
                if (ex.Response == null || ex.Status != WebExceptionStatus.ProtocolError) 
                    throw;
                return (HttpWebResponse) ex.Response;
            }
        }

Does an internet connection a necessity for bvcms? I mean, the web app appears to be querying sites when started, and it seems so slow because of this.(Internet speed not good). Is there any documentation out there that explains the basic behavior of bvcms?

**Comment by davidcarroll** [comment]
Many of the assets (Javascript, CSS, etc.) are retrieved via Content Delivery Networks (CDN). Bootstrap, jQuery, CkEditor are all not part of the repository but delivered at runtime across the Internet. That said, they should cache in the local browser after it is successfully delivered the first time.

So, the answer is yes, an Internet connection is required since the application is a Web-based application.

**Comment by allanregistos** [comment]
Thank you David for the quick response. That explains the cdn queries I saw. 
Mark this as solved.

**Comment by davidcarroll** [comment]
By the way, I am able to run and debug in my development environment even without an Internet connection because the browser (Chrome) is not attempting to re-fetch the assets from CDN since they are already cached.

**Comment by davidcarroll** [comment]
I just realized where that code is being called from. It is trying to read the News feed from the our blog to display on the home page. If you don't have Internet, you could comment out that code while developing with
```
#ifdef DEBUG
#else
// put the code here that you don't want to run in debug mode
#endif
```
