### ISSUE TITLE
Input for Add Recipient to Email

### ISSUE THREAD

**Issue by hkouns** [bvcms/bvcms#82]
@davidcarroll and @karenworrell ,

@nehresma and I are working on the Add Email Recipient feature and have it basically working at this point.  We would like your input on a couple items before submitting the pull request.

First, our assumptions:
- People will be added via the Search/Add Dialog box. 
- Emails will be tracked on the Added Recipient
- Opens/Fails/Etc of the Added Recipients will be tracked just like a recipient selected the standard methods.
- The feature is primarily to add a couple last minute names to an email ... as such we do not currently plan to save the Additional Recipients when saving a draft.   That added complexity could be added as a later feature.

Currently we are showing the Added Recipients in a List under the Multi-Select Box for standard emails... and the Add button is just a "Plus" sign input group add on 

![emailaddrecipient](https://cloud.githubusercontent.com/assets/5140785/12589699/15adfb22-c42d-11e5-8ebc-5d4a2cd7b431.png)

For a "Send to Current Org Members" email the Add Button is shown under the Alert box.
![emailaddrecipient_orgmember](https://cloud.githubusercontent.com/assets/5140785/12589700/15b6c27a-c42d-11e5-8ad7-8feb84659e02.png)

Also, Added Recipients can be removed by clicking the red "x" beside their name.

Do you have any input/suggestions/questions about where we are going with this feature?  Do you have any direction on the formatting that we should consider?

Thanks in advance.

**Comment by davidcarroll** [comment]
Heath,

Looks nice. I am sure @karenworrell would be happy to test this. Do you have a place where you can publish your development site online so that she can test it there? That is how we work here with multiple developers. Each one has their test database and IIS site. This way Karen can work with other developers without having to get me involved until it has passed her muster.

If you don't have such a place, perhaps we need to stand up a site on Rackspace that you can have access to and publish.

**Comment by davidcarroll** [comment]
I have a spare VM on our managed hypervisor on Rackspace. 
I created a ticket for Rackspace to add a new VPN that you will be able to copy your executable code to with a Network drive. I'll let you know when that is set up.

**Comment by hkouns** [comment]
Excellent!  We will install to that site when ready and get Karen to test.

In the meantime, if either of you have preliminary thoughts on the formatting or functionality, just let us know.

In Christ,

Heath

**Comment by davidcarroll** [comment]
I am getting close to having this VM setup for you to use. I use a MacBook Pro with Parallels and Windows 10 VM. So I use the Mac side to connect to the VPN, and since Parallels uses the Mac's network, I can get in from Windows. Apparently the Mac support for VPN is built-in. But on Windows, you have to have a Cisco AnyConnect client. Do you use a Mac? If so, that makes things easy. Otherwise, we will need to get the AnyConnect client.

**Comment by hkouns** [comment]
@davidcarroll, unfortunately I do not use Mac.  I do not know if @nehresma has a mac machine or not... but I am pretty sure he is using Linux with a Windows VM.

**Comment by davidcarroll** [comment]
No problem. I'll get the AnyConnect clients. We get two licenses for free from Rackspace.

**Comment by davidcarroll** [comment]
Heath, which email should I use to send you the credentials?

**Comment by davidcarroll** [comment]
just send it to me at david at bvcms.com

**Comment by davidcarroll** [comment]
Heath, glad you are connected the test environment.  Let us know when you are ready for us to test.

**Comment by hkouns** [comment]
David, based on our testing we have recently made a couple more changes that I will soon publish to the test environment and verify again myself.  Those include:
- Making it work properly with scheduled emails, 
- Disabling the Send button after successful email  (based on discussion in [another thread](https://github.com/bvcms/bvcms/pull/75#issuecomment-160202955) )

In order to facilitate further testing... we are also planning to incorporate the CC/ReplyTo Changes (https://github.com/bvcms/bvcms/pull/75)  into this branch.  We would then cancel the existing pull request and issue a new PR after all testing is completed on the combined features. Is this approach acceptable with you?  (I figured it would be best to document/release them together anyway)

I am hoping to ask you and Karen to test later this week.

**Comment by davidcarroll** [comment]
FYI, that test box is not running the batch service which is what is required to get scheduled emails to work. 

I am fine with your plan on the pull requests. Once it is tested and approved, a single pull request, where your branch has been rebased onto the latest master will work nicely. It still needs to be a separate branch so that I can pull and review the code before putting it in production.

Thanks

**Comment by hkouns** [comment]
@davidcarroll part of the solution for tracking the CC'd addresses was to add a column to the dbo.EmailQueue table.
The script that I used to add the column is located [here](https://github.com/GSBCfamily/bvcms/blob/add_cc_to_add_recipients/SqlScripts/BuildDb/Adding_cclist_columntodbo_EmailQueue.sql).

What is your preferred method for handling the schema migration on the test database?  Are the SQL Server management tools installed on the test server?  Do you want to test the migration yourself?  or should we do it?

Right now, it looks like I will publish the new code to the test site sometime tomorrow.

**Comment by davidcarroll** [comment]
I use Red-Gate SQL Compare and Multi-Script. Go ahead and make whatever schema changes in the database on the VM and I will use the SQL Compare product to produce a migration script to run on all databases. No need to do that until we get ready to go to production.

**Comment by hkouns** [comment]
@davidcarroll just to clarify:...You mention above about Rebasing the branch on the master.  Do you truly want it rebased? or is merging the latest master into the branch sufficient?

We can do it either way.  However, because we had merged a couple development branches... a standard rebase was getting tricky...so we had to squash all the changes into a single commit.

Doesn't matter too much... just wondering if you feel strongly one way or the other and making sure we are use the same definition.  ;-)

**Comment by davidcarroll** [comment]
No problem. Merge will be fine.

**Comment by hkouns** [comment]
ok.. .thanks.

By the way.  I just published the code to the Test Server for your review.   I sent an email with suggested tests to you and @karenworrell along with my test results.

Please, let us know what you think.

**Comment by davidcarroll** [comment]
@karenworrell is going to love you for outlining the testing plan like that.
She will tell you that I make her read my mind (sheepish grin).
She's actually pretty good at that!

In all seriousness, thank you very much.

**Comment by hkouns** [comment]
Based on Karen's successful evaluation of the code on the test server. I have issued a pull requesthttps://github.com/bvcms/bvcms/pull/86 and will close this issue.
