### ISSUE TITLE
[New Email Features]  CC Feature not working on Scheduled emails.

### ISSUE THREAD

**Issue by hkouns** [bvcms/bvcms#87]
Tested sending an email to myself as original Recipient... Added recipients Penny and @nehresma ...  then CC'd Logan (at) kounsfamily (dot) net.

Sent essentially the same email two ways:
1)  Sent Immediately... the email came through perfectly and all features worked.  (Additional Recipients get email, CC'd person gets email, CC'd address is added to ReplyTo,  "This Email was CC'd  email was CC'd..." note was added to body) 

2)  Scheduled for 5 minutes in the future.
 ^^^  The Schedule portion worked... it came through at the right time.
 ^^^  The Email went to the correct  Recipients...
 ^^^  The CC'd address was validated correctly... it is persisted and saved correctly with the Email Details.  (when you go to the  Detail page, it says the email was CC'd to Logan)

 xxx  HOWEVER, the CC'd Address does not actually get added to the Reply to Field.
 xxx  The "This email was CC'd..." note does not get added to body of email.
 xxx   A copy of the email is not sent to the CC'd address

Reference #86

**Comment by davidcarroll** [comment]
OK, the batch service is calling SendPeopleEmail but it does not know anything about the cclist. You are passing the cclist to the SendPeopleEmail function after the EmailQueue has already been built. But it is when the EmailQueue is built that you need to save the cclist in the EmailQueue object.

So the fix is to pass the cclist to the CreateQueue function and not in the SendPeopleEmail function. That way, the batch service and the SendPeopleEmail will have everything it needs in the EmailQueue to do the job.

**Comment by nehresma** [comment]
Looking into it now.  Should have a fix shortly.

**Comment by davidcarroll** [comment]
I have published this on production, both on the website and in the batch service. It is still a dark feature. Today, our goal is to 
* finish testing the scheduled emails and to 
* complete the documentation and 
* write a blog post announcing the new feature. 
* We will remove the developer only restriction right before issuing the new blog post.

Thank you @nehresma for the quick turnaround this!

**Comment by nehresma** [comment]
Sure thing!

**Comment by karenworrell** [comment]
CC'd message is displaying on emails even when no one is CC'd and the box is not checked.

**Comment by nehresma** [comment]
PR #89 should fix this.  Nice catch Karen.  It was an unintended side effect from the change this morning.

**Comment by karenworrell** [comment]
This is fixed. Thank you.
