### ISSUE TITLE
Parent emails are not getting sent when using email child > cc parents from blue toolbar

### ISSUE THREAD

**Issue by karenworrell** [bvcms/bvcms#90]
@nehresma & @hkouns 
This is when I use that selection from the blue toolbar. I tested without either an added person or a cc/reply-to address. I also tested with each of those. In each case, the child email was sent, but not the email to the parents. However, on the Email Details page, it does show the parents listed beside the child's name.

**Comment by davidcarroll** [comment]
Let me look first. There was some tricky logic that heath added when he added the ability to see the altemail when there was no primary email.

**Comment by karenworrell** [comment]
This works now. Reverting to previous code seems to have fixed it.
