### ISSUE TITLE
Will you consider accepting a PR to improve the AddContributions API call?

### ISSUE THREAD

**Issue by rastographics** [bvcms/bvcms#933]
Hi, I would like to do a PR for a simple change if you are interested in accepting it.

I'm have our own giving page and just started using [this API](https://docs.touchpointsoftware.com/CustomProgramming/API/ApiPushPost.html) to create contribution records in touchpoint every time a member gives on our page.

Currently, in touchpoint API, a search is done on every call to find a matching person based on name, email, phone, etc.

I'd like to be able to (manually) save church member's touchpoint PeopleID to their profile on our own website login system. Then, when they give on our site, I would submit that PeopleID to the touchpoint api when creating a contribution.

The changes to the code would only require checking if a PeopleID parameter was present, and if so, then loading that person by PeopleID. (and skip the FindPerson call if a person is found by ID).

At this line:
https://github.com/bvcms/bvcms/blob/develop/CmsWeb/Models/Api/AddContributionModel.cs#L37

This will resolve any potential problems with incorrect matches or finding no matches, or handling non-members who do not have touchpoint accounts (and I don't want their giving information entered into our touchpoint system. We have people all over the country who give to our missionaries for example, and their giving shouldn't be in touchpoint for us).

I'm willing to make these changes and test them. I've already contributed to this codebase in the past by adding an additional gateway provider (BluePay) that we've been using for several years now.

Please let me know, and if so I'll do the PR and submit. 

Thanks!

**Comment by brondavies** [comment]
Yes, please, that would be a nice improvement.

**Comment by rastographics** [comment]
PR added here: https://github.com/bvcms/bvcms/pull/989

CodeFactor is flagging it for a "Complex Method" although I'm not really sure what method it is referring to.

**Comment by brondavies** [comment]
Merged PR #989 - I'll let you know when it's been deployed @rastographics

**Comment by rastographics** [comment]
Great thank you!
