### ISSUE TITLE
Oauth2 Authentication flow on the roadmap?

### ISSUE THREAD

**Issue by rastographics** [bvcms/bvcms#98]
I know there is a method in place to authenticate on a 3rd-party website via bvcms credentials.
http://docs.touchpointsoftware.com/API/API-OneTimeLink.html

I'm using [Auth0](http://auth0.com) for other web apps our church has. It would be great if bvcms used oauth2, allowing Auth0 users to connect their Auth0 login to their bvcms credentials. [Using custom identity provider with Auth0](https://auth0.com/docs/connections/social/oauth2)

Given how popular Auth0 is becoming (and especially oauth2), it seems like a worthwhile venture to have that available with bvcms (could use something like IdentityServer3).

I'm just one developer and user of touchpoint, but maybe others are looking for oauth2 authentication and would chime in?

Willing to put time into this project if it is something that would get pulled in.

**Comment by stevesloka** [comment]
@rastographics I would be interested in this as well. My church is looking to build some apps and integrate back, so I could help out with this as well.

**Comment by rastographics** [comment]
Would be great to have Touchpoint listed as a social provider in Auth0 right alongside Google and the others. I didn't realize but ACS has ["The City" integration already ](https://auth0.com/docs/connections/social/thecity)

Another benefit of going through Auth0: I have some sites I want to authenticate all kinds of people not just church members. But I don't want a bunch of non-members making bvcms accounts just to login to these other resources. So Auth0 would give me a way to easily let non-members make a quick "Auth0" account, and bvcms members could just use their existing credentials. 
I'll wait for someone on core team to chime in before I get too carried away, but I think this could be really great for bvcms.

**Comment by davidcarroll** [comment]
We would be delighted for you guys to work on this project for OAuth. We don't have much time to help you coding this but it would be a nice feature to have. We have used OAuth a few years ago when we were working on a QuickBooks integration and it was really difficult and flaky at the time, but obviously, I like how it works with StackOverflow and Trello for credentials.

I just published a PullRequestGuidelines file in the repo to let you know how we would work with you on this. See https://github.com/bvcms/bvcms/blob/master/PullRequestGuidelines.md

**Comment by rastographics** [comment]
Sounds good. I found out how to get a "Touchpoint" provider listed with the built-in social providers for Auth0. It's pretty simple. So the hard work will be getting bvcms to issue and validate Oauth2 tokens. 

I'm thinking the best way to go would be integrate the excellent [IdentityServer3](https://github.com/IdentityServer/IdentityServer3) framework. It's open source and has nuget packages. I've been following it for a while but haven't used in any projects yet. I suggest watching the videos if anyone wants to wrap their head around the concepts.

It handles all the oauth2 and openidconnect plumbing. We just need to point it at the users in the database and specify what "clients" (apps) would be requesting tokens (this will require a AppClients table added to the database).

@stevesloka Whats a good way to collaborate with you? Trello?

**Comment by davidcarroll** [comment]
Speaking of wrapping my head around this, here is my question. Since each church has their own database and authenticates against the saved credentials (encrypted), in their own database, does this mean that each "church" would be their own identity server provider? In other words, a user in a church does not authenticate against TouchPoint the hosting company and hosting provider, but rather the individual church since there is no sharing of data between users on the different churches. 

Also, I am unclear as to what external applications we would be providing credentials for? The AppClients table would be added to the church's database and each church would maintain their own list of web apps that could request tokens. I am assuming this is just to gain access to the TouchPoint API.

Finally, if we are talking about having thousands of IdentityServers providing authentication (each church), would each one need to be listed in the Auth0?

**Comment by rastographics** [comment]
From Auth0 perspective, touchpoint would be providing an easy way for individual churches to authenticate against their individual databases. Touchpoint would be listed in Auth0 only once as a social provider. Developers for individual churches can then implement the "Touchpoint" provider and would have to configure it to work against their church's database.

Typically, Touchpoint would have a "API" section in the Settings area. 
There, the church's individual urls for Auth and Token endpoints could be displayed (ie, bellevue.bvcms.com/auth/token, etc). Furthermore, a church would add one or more "clients" (apps) which could send/receive auth tokens. Each client is given an auto-generated ID and Secret. 

The church's developer would simply put that church's auth/token url, and client ID/secret in the dashboard on Auth0 to configure their "Touchpoint provider".

This could be used for TouchPoint API but that is not the only (or primary) use case. It allows church's to have multiple mobile apps and/or websites that allow just their church members to log in with their touchpoint credentials. Or allow a mix of church members and non-members, but give the members special privileges. And the 3rd party apps never see the touchpoint credentials.

For instance, I would like to put our prayer requests on the website, but due to sensitive nature of some, it is not great to have that visible to the whole world. To lock down by username and password is OK, but I still can't verify that people who create logins are actual members.

But if someone logged into my site using touchpoint credentials, my application can look at their member status, and if they are a member, allow them to see all the prayer requests. 

Same thing goes for our sermon archive that uses a custom website. 

Typically, logging in could also give the 3rd-party app some basic interesting information about the church member (if the developer so chooses to ask for it). Name, email, birthday, other profile information. But the member would be prompted to agree to that when first entering his credentials for Touchpoint.

I think the big value of authenticating 3rd party stuff through Touchpoint is that the 3rd party would be able to trust the user is who they say they are, since that has all been vetted so thoroughly when the Touchpoint user was first created.

**Comment by davidcarroll** [comment]
Ah, that was very helpful @rastographics.

**Comment by davidcarroll** [comment]
I am closing this issue since it was resolved with a plan.

**Comment by rastographics** [comment]
@stevesloka I've been digging into Auth0 lately and thinking more on this topic. I'm considering an attempt at this since I really need it for our church. You expressed desire in this last year, wondering if you ever attempted anything with this, or did you go a different direction for your apps? or if Auth0 integration is still even something that would be helpful to you?

**Comment by stevesloka** [comment]
Hey @rastographics, sorry lost track of this completely. I think this would be super helpful for us. Did you want to try and pick it back up? I can help work on it.

**Comment by davidcarroll** [comment]
We may have a sponsored project from a couple of churches looking in to doing this. I'll update here when it gets off the ground. We will probably outsource this to someone who already has experience developing this functionality.

**Comment by rastographics** [comment]
@stevesloka  I've been doing a lot of projects using Auth0 and have a pretty solid understanding now of how everything works, but haven't been able to look into integrating it with touchpoint yet.
@davidcarroll that sounds amazing. i'm definitely willing to be a early alpha/beta tester and implementer if you need that.

**Comment by stevesloka** [comment]
Sounds good everyone! If it's on the roadmap to come then please don't want to stop the progress. I'm interested when it's ready to play with, we'll be a consumer of it.
